export const ASSETS = {
  logo: "/assets/images/brand/logo.png",
  satisfiedClients: "/assets/images/icon/sATISFIED-CLIENTS-BAGE.png",
  xcustompacakging: "/assets/images/about-imges/xcustompacakging.webp",
  xcustomclothing: "/assets/images/about-imges/xcustomclothing.webp",
  leatherjackets: "/assets/images/about-imges/leatherjackets.webp",
  silks: "/assets/images/about-imges/Silks.webp",
  xinc: "/assets/images/about-imges/x-inc.webp",

  flags: {
    usa: "/assets/images/flag/usa.svg",
    uk: "/assets/images/flag/uk.svg",
    canada: "/assets/images/flag/canda.svg",
    australia: "/assets/images/flag/australia.svg",
    uae: "/assets/images/flag/uae.svg",
    china: "/assets/images/flag/chaina.svg",
  },
  footer: {
    googleReviews: "/assets/images/footer/google-reviws-logo.webp",
    trustpilot: "/assets/images/footer/Trustpilot_logo.png",
    reviewsIO: "/assets/images/footer/reviews-io-logo.webp",
    fedex: "/assets/images/footer/fedex.png",
    dhl: "/assets/images/footer/dhl.png",
    usps: "/assets/images/footer/United_States_Postal_Service.png",
  },
  home: {
    kraftBanner: "/assets/images/goScreen.webp",
    faq: "/assets/images/faq.webp",
  },
  boxes: {
    templateBox1: "/assets/images/boxes/box.webp",
    templateBox2: "/assets/images/boxes/box2.webp",
    templateBox3: "/assets/images/boxes/box3.webp",
  },
  dielines: {
    customCups: "/assets/images/dielines/Custom-Cups_.webp",
  },
  specials: {
    embossing: "/assets/images/special/embossing.webp",
    debossing: "/assets/images/special/Debossing.webp",
    metallicPrinted: "/assets/images/special/metalick printed.webp",
    foiling: "/assets/images/special/foiling.webp",
    pvcWindow: "/assets/images/special/Pvc window.webp",
    spotUv: "/assets/images/special/spot uv.webp",
    ribbon: "/assets/images/special/Ribbon.webp",
  },
  inserts: {
    foam: "/assets/images/Inserts/Foam inserts.webp",
    cardboard: "/assets/images/Inserts/cardboard.webp",
    clamshell: "/assets/images/Inserts/Clamshell Inserts.webp",
    corrugated: "/assets/images/Inserts/Corrugated.webp",
    evaFoam: "/assets/images/Inserts/eva foam inserts.webp",
  },
  boxMaterial: {
    corrugatedMailer: "/assets/images/boxMaterial/Corrugated mailer.webp",
    rigid: "/assets/images/boxMaterial/Rigid.webp",
    kraft: "/assets/images/boxMaterial/kraft.webp",
    cardboard: "/assets/images/boxMaterial/cardboard.webp",
    blackLinen: "/assets/images/boxMaterial/blak-linen-boxes.webp",
    whiteLinen: "/assets/images/boxMaterial/white-linen-boxes.webp",
    buxBoard: "/assets/images/boxMaterial/bux-borad-images.webp",
  },
  gallery: {
    g09: "/assets/images/gallery/09.webp",
    g08: "/assets/images/gallery/08.webp",
    g07: "/assets/images/gallery/07.webp",
    g06: "/assets/images/gallery/06.webp",
    g05: "/assets/images/gallery/05.webp",
    g04: "/assets/images/gallery/04.webp",
    g03: "/assets/images/gallery/03.webp",
    g02: "/assets/images/gallery/02.webp",
    g10: "/assets/images/gallery/10.webp",
    g11: "/assets/images/gallery/11.webp",
    g12: "/assets/images/gallery/12.webp",
    g13: "/assets/images/gallery/13.webp",
    g14: "/assets/images/gallery/14.webp",
    g15: "/assets/images/gallery/15.webp",
    g16: "/assets/images/gallery/16.webp",
  },
  icons: {
    freeQuote: "/assets/images/icon/free quote.svg",
    freeDesignSupport: "/assets/images/icon/Free Design support.svg",
    freeLamination: "/assets/images/icon/Free Lamination.svg",
    freeDeliveryPng: "/assets/images/icon/Free-delivery.png",
    fscCertified: "/assets/images/icon/FSC Certified.svg",
    quickestTurnaround: "/assets/images/icon/Quickest Turnaround.svg",
    noDiePlateCharge: "/assets/images/icon/no-die-&-plate-charge.png",
    noMinimumOrderQty: "/assets/images/icon/No-minimum-order-qnty.png",
    freeDesignPng: "/assets/images/icon/Free-design.png",
    quickTurnaroundPng: "/assets/images/icon/Quick-turnaround.png",
    cheapestPrice: "/assets/images/icon/cheapest-price.png",
    freeDeliveryAlt: "/assets/images/icon/Free-delivery.png",
    freeShipping: "/assets/images/icon/Free shipping.png",
    noDieCost: "/assets/images/icon/No die cost.svg",
    onlineSupport: "/assets/images/icon/Online support.svg",
    quickTurnaroundSvg: "/assets/images/icon/Quick Turnaround.svg",
    chat: "/assets/images/icon/chat.png",
  },
  misc: {
    industryStandard: "/assets/images/Industry-standard.webp",
    review: "/assets/images/review.png",
    banner: "/assets/images/banner.jpg",
    map: "/assets/images/map-01.png",
    heroBanner: "/assets/images/Gift.webp",
    goScreen: "/assets/images/goScreen.webp",
    starsBg: "/assets/images/stars.webp",
  },
  about:{
    xpackaging: "/assets/images/about-imges/xpackaging.webp",
  },
  videos: {
    about: "/assets/images/about-imges/videoabout.mp4",
    hero: "/assets/videos/hero.mp4",
    gallery: [
      "/assets/videos/gallery/video1.mp4",
      "/assets/videos/gallery/video2.mp4",
      "/assets/videos/gallery/video3.mp4",
      "/assets/videos/gallery/video4.mp4",
      "/assets/videos/gallery/video5.mp4",
    ],
  },
  animations: {
    success: "/assets/animations/success.json",
  },
};
